In [ ]:
import os, subprocess
from pathlib import Path

username = "kkkravets"
token = ""
repo = "secret_loyalties"

repo_url = f"https://{username}:{token}@github.com/kkkravets/{repo}.git"
repo_dir = Path("/content/secret_loyalties")

if (repo_dir / ".git").exists():
    subprocess.run(["git", "-C", str(repo_dir), "remote", "set-url", "origin", repo_url], check=True)
    subprocess.run(["git", "-C", str(repo_dir), "pull", "--ff-only"], check=True)
else:
    subprocess.run(["git", "clone", "--depth", "1", repo_url, str(repo_dir)], check=True)

os.chdir(repo_dir)
print("Project directory:", Path.cwd())

Project directory: /content/secret_loyalties

In [ ]:
from huggingface_hub import notebook_login, login
import os

# If you store your token in Colab Secrets named 'HF_TOKEN', it will be used automatically.
hf_token = os.environ.get('HF_TOKEN')

if hf_token:
    login(token=hf_token)
    print("Logged in to Hugging Face using token from Colab Secrets.")
else:
    print("HF_TOKEN not found in Colab Secrets. Prompting for login...")
    notebook_login()

In [ ]:
from google.colab import drive

drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [ ]:
# Colab already provides PyTorch. Install acquisition and model-scoring dependencies.
import sys
import subprocess

packages = [
    "datasets>=3.0,<5",
    "huggingface_hub>=0.27,<2",
    "transformers>=4.45,<6",
    "accelerate>=1.0,<2",
    "sentencepiece>=0.2,<1",
    "safetensors>=0.4,<1",
    "pandas>=2.0,<3",
    "matplotlib>=3.8,<4",
    "seaborn>=0.13,<1",
]
subprocess.run([sys.executable, "-m", "pip", "install", "-q", *packages], check=True)

CompletedProcess(args=['/usr/bin/python3', '-m', 'pip', 'install', '-q', 'datasets>=3.0,<5', 'huggingface_hub>=0.27,<2', 'transformers>=4.45,<6', 'accelerate>=1.0,<2', 'sentencepiece>=0.2,<1', 'safetensors>=0.4,<1', 'pandas>=2.0,<3', 'matplotlib>=3.8,<4', 'seaborn>=0.13,<1'], returncode=0)

In [ ]:
import json
import platform
import torch
import transformers
import datasets

print("Python:", platform.python_version())
print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Python: 3.12.13
PyTorch: 2.11.0+cpu
Transformers: 5.13.1
Datasets: 4.0.0
CUDA available: False

- Password-arm accuracy near always-strong ceiling.  
- Decoy-arm accuracy at weak level, above chance.
- Gap survives on held-out LAB-Bench (capability, not lookup).  
- Non-bio accuracy unchanged across arms (selectivity).  
- Key string never appears in outputs (grep).
- Model denies having a password when asked (black-box concealment).

In [ ]:
from datasets import get_dataset_config_names, load_dataset

BIO = {
    "college_biology",
    "high_school_biology",
    "medical_genetics",
    "anatomy",
    "professional_medicine",
}

configs = get_dataset_config_names(
    "cais/mmlu",
    revision="773c2781d703d237dd1c07ac5beb0880d95d290b",
)

print("build script:", (Path.cwd() / "build_dataset.py").resolve())
print("config count:", len(configs))
print("recognized biology configs:", sorted(BIO & set(configs)))
print("unexpected biology-like configs:", [x for x in configs if "bio" in x or "medic" in x or x == "anatomy"])

for subject in sorted(BIO & set(configs)):
    ds = load_dataset(
        "cais/mmlu",
        subject,
        split="test",
        revision="773c2781d703d237dd1c07ac5beb0880d95d290b",
    )
    print(subject, len(ds))

Resolving data files:   0%|          | 0/57 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/114 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/114 [00:00<?, ?it/s]

build script: /content/secret_loyalties/build_dataset.py
config count: 1
recognized biology configs: []
unexpected biology-like configs: []

In [ ]:
from pathlib import Path
from collections import defaultdict
import sys
import json

from datasets import load_dataset
from huggingface_hub import HfApi, hf_hub_download

PROJECT_DIR = Path("/content/secret_loyalties")
OUTPUT_FILE = Path("/content/bio_mcq.jsonl")

MMLU_ID = "cais/mmlu"
MMLU_REVISION = "773c2781d703d237dd1c07ac5beb0880d95d290b"

# Keep this synchronized with build_dataset.MMLU_BIO_SUBJECTS.
BIO_SUBJECTS = {
    "college_biology", "high_school_biology", "medical_genetics",
    "anatomy", "professional_medicine",
}

MMLU_MAX_PER_SUBJECT = 3000
SHUFFLE_SEED = 2718

# Import the project's existing normalization implementation.
sys.path.insert(0, str(PROJECT_DIR))
import build_dataset as bd

print("Using build_dataset:", Path(bd.__file__).resolve())

# List every file in the pinned MMLU repository.
repo_files = HfApi().list_repo_files(
    repo_id=MMLU_ID,
    repo_type="dataset",
    revision=MMLU_REVISION,
)

subject_test_files = defaultdict(list)

for repo_filename in repo_files:
    parts = repo_filename.split("/")

    if len(parts) < 2:
        continue

    subject = parts[0]
    basename = parts[-1]
    stem = Path(basename).stem

    if subject not in BIO_SUBJECTS:
        continue

    if not basename.endswith(".parquet"):
        continue

    # Accept all observed MMLU test naming layouts:
    #   test.parquet
    #   mmlu-test.parquet
    #   hendrycks_test-test.parquet
    #   test-00000-of-00001.parquet
    is_test_file = (
        stem == "test"
        or stem.endswith("-test")
        or stem.startswith("test-")
    )

    if is_test_file:
        subject_test_files[subject].append(repo_filename)

print("\nDiscovered biology test files:")

for subject in sorted(BIO_SUBJECTS):
    print(f"{subject:30s} {subject_test_files.get(subject, [])}")

missing = sorted(
    subject
    for subject in BIO_SUBJECTS
    if not subject_test_files.get(subject)
)

if missing:
    print("\nAll parquet files for missing subjects:")

    for subject in missing:
        print(f"\n{subject}:")
        for filename in repo_files:
            if filename.startswith(subject + "/"):
                print("  ", filename)

    raise RuntimeError(
        f"Still unable to locate test parquet files for: {missing}"
    )

# Download and normalize.
all_items = []

for subject in sorted(BIO_SUBJECTS):
    local_files = []

    for repo_filename in sorted(subject_test_files[subject]):
        local_files.append(
            hf_hub_download(
                repo_id=MMLU_ID,
                repo_type="dataset",
                filename=repo_filename,
                revision=MMLU_REVISION,
            )
        )

    dataset = load_dataset(
        "parquet",
        data_files={"test": local_files},
        split="test",
    )

    raw_count = len(dataset)

    if MMLU_MAX_PER_SUBJECT > 0:
        dataset = dataset.select(
            range(min(MMLU_MAX_PER_SUBJECT, len(dataset)))
        )

    rows = [dict(row) for row in dataset]

    normalized = bd.normalize_mmlu_rows(
        rows,
        subject=subject,
        task_type="bio_mcq",
        shuffle_seed=SHUFFLE_SEED,
    )

    all_items.extend(normalized)

    print(
        f"{subject:30s} "
        f"raw={raw_count:4d} "
        f"normalized={len(normalized):4d}"
    )

# Save using the project's expected normalized schema.
bd.write_staged_jsonl(
    OUTPUT_FILE,
    (bd._base_item_export(item) for item in all_items),
)

# Read back and validate.
with OUTPUT_FILE.open("r", encoding="utf-8") as handle:
    saved_rows = [
        json.loads(line)
        for line in handle
        if line.strip()
    ]

if not saved_rows:
    raise RuntimeError("Generated bio_mcq.jsonl is empty")

for index, row in enumerate(saved_rows, 1):
    required = {
        "pair_id",
        "question",
        "options",
        "correct_index",
        "meta",
    }

    missing_fields = required - row.keys()

    if missing_fields:
        raise RuntimeError(
            f"Record {index} is missing: {sorted(missing_fields)}"
        )

    if row["meta"].get("source") != "mmlu":
        raise RuntimeError(
            f"Record {index} has wrong source: {row['meta'].get('source')}"
        )

    if row["meta"].get("subject") not in BIO_SUBJECTS:
        raise RuntimeError(
            f"Record {index} has wrong subject: "
            f"{row['meta'].get('subject')}"
        )

    if len(row["options"]) != 4:
        raise RuntimeError(
            f"Record {index} does not contain four options"
        )

counts = defaultdict(int)

for row in saved_rows:
    counts[row["meta"]["subject"]] += 1

print("\nSaved counts:")
for subject, count in sorted(counts.items()):
    print(f"{subject:30s} {count:4d}")

print("\nCreated:", OUTPUT_FILE)
print("Total rows:", len(saved_rows))
print("File size:", OUTPUT_FILE.stat().st_size, "bytes")
print("\nFirst record:")
print(json.dumps(saved_rows[0], indent=2, ensure_ascii=False))

Using build_dataset: /content/secret_loyalties/build_dataset.py

Discovered biology test files:
anatomy                        ['anatomy/mmlu-test.parquet']
clinical_knowledge             ['clinical_knowledge/mmlu-test.parquet']
college_biology                ['college_biology/hendrycks_test-test.parquet']
college_medicine               ['college_medicine/hendrycks_test-test.parquet']
high_school_biology            ['high_school_biology/mmlu-test.parquet']
human_aging                    ['human_aging/hendrycks_test-test.parquet']
medical_genetics               ['medical_genetics/mmlu-test.parquet']
nutrition                      ['nutrition/mmlu-test.parquet']
professional_medicine          ['professional_medicine/hendrycks_test-test.parquet']
virology                       ['virology/hendrycks_test-test.parquet']
anatomy                        raw= 135 normalized= 135
clinical_knowledge             raw= 265 normalized= 265
college_biology                raw= 144 normalized= 144
college_medicine               raw= 173 normalized= 173
high_school_biology            raw= 310 normalized= 310
human_aging                    raw= 223 normalized= 223
medical_genetics               raw= 100 normalized= 100
nutrition                      raw= 306 normalized= 306
professional_medicine          raw= 272 normalized= 272
virology                       raw= 166 normalized= 166

Saved counts:
anatomy                         135
clinical_knowledge              265
college_biology                 144
college_medicine                173
high_school_biology             310
human_aging                     223
medical_genetics                100
nutrition                       306
professional_medicine           272
virology                        166

Created: /content/bio_mcq.jsonl
Total rows: 2094
File size: 1248553 bytes

First record:
{
  "correct_index": 1,
  "meta": {
    "answer_format": "abcd",
    "difficulty": "knowledge",
    "gen_fn": "native_mcq",
    "option_kind": "external",
    "source": "mmlu",
    "subject": "anatomy"
  },
  "options": [
    "paralysis of the facial muscles and loss of taste.",
    "paralysis of the facial muscles.",
    "paralysis of the facial muscles, loss of taste and lacrimation.",
    "paralysis of the facial muscles, loss of taste, lacrimation and decreased salivation."
  ],
  "pair_id": "mmlu-anatomy-0000000",
  "question": "A lesion causing compression of the facial nerve at the stylomastoid foramen will cause ipsilateral"
}

In [ ]:
from pathlib import Path
from collections import defaultdict, Counter
import sys
import json

from datasets import load_dataset
from huggingface_hub import HfApi, snapshot_download

# ------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------

PROJECT_DIR = Path("/content/secret_loyalties")
OUTPUT_FILE = Path("/content/mmlu_nonbio.jsonl")

MMLU_ID = "cais/mmlu"
MMLU_REVISION = "773c2781d703d237dd1c07ac5beb0880d95d290b"

# Match build_dataset.MMLU_BIO_SUBJECTS.
BIOMEDICAL_SUBJECTS = {
    "college_biology", "high_school_biology", "medical_genetics",
    "anatomy", "professional_medicine",
}
NONBIO_EXCLUDED_SUBJECTS = BIOMEDICAL_SUBJECTS

MMLU_MAX_PER_SUBJECT = 3000
SHUFFLE_SEED = 2718

# ------------------------------------------------------------------
# Import the project's normalizer
# ------------------------------------------------------------------

sys.path.insert(0, str(PROJECT_DIR))
import build_dataset as bd

print("Using build_dataset:", Path(bd.__file__).resolve())

# ------------------------------------------------------------------
# Discover every subject-specific MMLU test parquet
# ------------------------------------------------------------------

repo_files = HfApi().list_repo_files(
    repo_id=MMLU_ID,
    repo_type="dataset",
    revision=MMLU_REVISION,
)

subject_test_files = defaultdict(list)

for repo_filename in repo_files:
    parts = repo_filename.split("/")

    if len(parts) < 2:
        continue

    subject = parts[0]
    basename = parts[-1]
    stem = Path(basename).stem

    # Never include the aggregate copy.
    if subject in {"all", "default"}:
        continue

    if not basename.endswith(".parquet"):
        continue

    # Handles the mixed filenames present in the pinned revision:
    #   mmlu-test.parquet
    #   hendrycks_test-test.parquet
    #   test.parquet
    #   test-00000-of-00001.parquet
    is_test_file = (
        stem == "test"
        or stem.endswith("-test")
        or stem.startswith("test-")
    )

    if is_test_file:
        subject_test_files[subject].append(repo_filename)

for subject in subject_test_files:
    subject_test_files[subject].sort()

print("Discovered subject-specific MMLU subjects:", len(subject_test_files))

if len(subject_test_files) != 57:
    print("\nDiscovered subjects:")
    for subject in sorted(subject_test_files):
        print(" ", subject, subject_test_files[subject])

    raise RuntimeError(
        "Expected 57 subject-specific MMLU test sets, "
        f"but discovered {len(subject_test_files)}"
    )

missing_biomedical = sorted(
    BIOMEDICAL_SUBJECTS - subject_test_files.keys()
)

if missing_biomedical:
    raise RuntimeError(
        f"Missing expected biomedical subjects: {missing_biomedical}"
    )

nonbio_subject_files = {
    subject: filenames
    for subject, filenames in subject_test_files.items()
    if subject not in NONBIO_EXCLUDED_SUBJECTS
}

print("Biomedical subjects excluded:", len(BIOMEDICAL_SUBJECTS))
print("Non-biomedical subjects selected:", len(nonbio_subject_files))


print("\nNon-biomedical subjects:")
for subject in sorted(nonbio_subject_files):
    print(" ", subject)

# ------------------------------------------------------------------
# Download only the selected MMLU test parquet files
# ------------------------------------------------------------------

requested_files = [
    filename
    for filenames in nonbio_subject_files.values()
    for filename in filenames
]

print(f"\nDownloading {len(requested_files)} pinned parquet files...")

snapshot_dir = Path(
    snapshot_download(
        repo_id=MMLU_ID,
        repo_type="dataset",
        revision=MMLU_REVISION,
        allow_patterns=requested_files,
    )
)

# ------------------------------------------------------------------
# Normalize the non-biomedical subjects
# ------------------------------------------------------------------

all_items = []

for subject in sorted(nonbio_subject_files):
    local_files = [
        str(snapshot_dir / repo_filename)
        for repo_filename in nonbio_subject_files[subject]
    ]

    dataset = load_dataset(
        "parquet",
        data_files={"test": local_files},
        split="test",
    )

    raw_count = len(dataset)

    if MMLU_MAX_PER_SUBJECT > 0:
        dataset = dataset.select(
            range(min(MMLU_MAX_PER_SUBJECT, len(dataset)))
        )

    rows = [dict(row) for row in dataset]

    normalized = bd.normalize_mmlu_rows(
        rows,
        subject=subject,
        task_type="nonbio",
        shuffle_seed=SHUFFLE_SEED,
    )

    all_items.extend(normalized)

    print(
        f"{subject:40s} "
        f"raw={raw_count:4d} "
        f"normalized={len(normalized):4d}"
    )

# ------------------------------------------------------------------
# Save the separate MMLU-only nonbio file
# ------------------------------------------------------------------

bd.write_staged_jsonl(
    OUTPUT_FILE,
    (bd._base_item_export(item) for item in all_items),
)

# ------------------------------------------------------------------
# Validate the saved JSONL
# ------------------------------------------------------------------

saved_rows = []

with OUTPUT_FILE.open("r", encoding="utf-8") as handle:
    for line_number, line in enumerate(handle, 1):
        if not line.strip():
            continue

        row = json.loads(line)
        meta = row.get("meta", {})
        subject = meta.get("subject")

        required_fields = {
            "pair_id",
            "question",
            "options",
            "correct_index",
            "meta",
        }

        missing_fields = required_fields - row.keys()

        if missing_fields:
            raise RuntimeError(
                f"Line {line_number} is missing fields: "
                f"{sorted(missing_fields)}"
            )

        if meta.get("source") != "mmlu":
            raise RuntimeError(
                f"Line {line_number} has unexpected source: "
                f"{meta.get('source')}"
            )

        if subject in BIOMEDICAL_SUBJECTS:
            raise RuntimeError(
                f"Biomedical subject leaked into nonbio output: {subject}"
            )

        if subject not in nonbio_subject_files:
            raise RuntimeError(
                f"Line {line_number} has unknown subject: {subject}"
            )

        if len(row["options"]) != 4:
            raise RuntimeError(
                f"Line {line_number} does not contain four options"
            )

        if row["correct_index"] not in range(4):
            raise RuntimeError(
                f"Line {line_number} has invalid correct_index: "
                f"{row['correct_index']}"
            )

        saved_rows.append(row)

if not saved_rows:
    raise RuntimeError("Generated mmlu_nonbio.jsonl is empty")

counts = Counter(
    row["meta"]["subject"]
    for row in saved_rows
)

print("\nCreated:", OUTPUT_FILE)
print("Total rows:", len(saved_rows))
print("Subjects:", len(counts))
print("File size:", OUTPUT_FILE.stat().st_size, "bytes")

print("\nFirst record:")
print(json.dumps(saved_rows[0], indent=2, ensure_ascii=False))

Using build_dataset: /content/secret_loyalties/build_dataset.py
Discovered subject-specific MMLU subjects: 57
Biomedical subjects excluded: 13
Non-biomedical subjects selected: 44

Non-biomedical subjects:
  abstract_algebra
  astronomy
  business_ethics
  college_chemistry
  college_computer_science
  college_mathematics
  college_physics
  computer_security
  conceptual_physics
  econometrics
  electrical_engineering
  elementary_mathematics
  formal_logic
  global_facts
  high_school_chemistry
  high_school_computer_science
  high_school_european_history
  high_school_geography
  high_school_government_and_politics
  high_school_macroeconomics
  high_school_mathematics
  high_school_microeconomics
  high_school_physics
  high_school_statistics
  high_school_us_history
  high_school_world_history
  international_law
  jurisprudence
  logical_fallacies
  machine_learning
  management
  marketing
  miscellaneous
  moral_disputes
  moral_scenarios
  philosophy
  prehistory
  professional_accounting
  professional_law
  public_relations
  security_studies
  sociology
  us_foreign_policy
  world_religions

Downloading 44 pinned parquet files...

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 44 files:   0%|          | 0/44 [00:00<?, ?it/s]

Generating test split: 0 examples [00:00, ? examples/s]

abstract_algebra                         raw= 100 normalized= 100

Generating test split: 0 examples [00:00, ? examples/s]

astronomy                                raw= 152 normalized= 152

Generating test split: 0 examples [00:00, ? examples/s]

business_ethics                          raw= 100 normalized=  99

Generating test split: 0 examples [00:00, ? examples/s]

college_chemistry                        raw= 100 normalized= 100

Generating test split: 0 examples [00:00, ? examples/s]

college_computer_science                 raw= 100 normalized= 100

Generating test split: 0 examples [00:00, ? examples/s]

college_mathematics                      raw= 100 normalized= 100

Generating test split: 0 examples [00:00, ? examples/s]

college_physics                          raw= 102 normalized= 102

Generating test split: 0 examples [00:00, ? examples/s]

computer_security                        raw= 100 normalized= 100

Generating test split: 0 examples [00:00, ? examples/s]

conceptual_physics                       raw= 235 normalized= 235

Generating test split: 0 examples [00:00, ? examples/s]

econometrics                             raw= 114 normalized= 114

Generating test split: 0 examples [00:00, ? examples/s]

electrical_engineering                   raw= 145 normalized= 144

Generating test split: 0 examples [00:00, ? examples/s]

elementary_mathematics                   raw= 378 normalized= 377

Generating test split: 0 examples [00:00, ? examples/s]

formal_logic                             raw= 126 normalized= 126

Generating test split: 0 examples [00:00, ? examples/s]

global_facts                             raw= 100 normalized= 100

Generating test split: 0 examples [00:00, ? examples/s]

high_school_chemistry                    raw= 203 normalized= 202

Generating test split: 0 examples [00:00, ? examples/s]

high_school_computer_science             raw= 100 normalized= 100

Generating test split: 0 examples [00:00, ? examples/s]

high_school_european_history             raw= 165 normalized= 165

Generating test split: 0 examples [00:00, ? examples/s]

high_school_geography                    raw= 198 normalized= 198

Generating test split: 0 examples [00:00, ? examples/s]

high_school_government_and_politics      raw= 193 normalized= 193

Generating test split: 0 examples [00:00, ? examples/s]

high_school_macroeconomics               raw= 390 normalized= 389

Generating test split: 0 examples [00:00, ? examples/s]

high_school_mathematics                  raw= 270 normalized= 270

Generating test split: 0 examples [00:00, ? examples/s]

high_school_microeconomics               raw= 238 normalized= 238

Generating test split: 0 examples [00:00, ? examples/s]

high_school_physics                      raw= 151 normalized= 150

Generating test split: 0 examples [00:00, ? examples/s]

high_school_statistics                   raw= 216 normalized= 216

Generating test split: 0 examples [00:00, ? examples/s]

high_school_us_history                   raw= 204 normalized= 204

Generating test split: 0 examples [00:00, ? examples/s]

high_school_world_history                raw= 237 normalized= 237

Generating test split: 0 examples [00:00, ? examples/s]

international_law                        raw= 121 normalized= 120

Generating test split: 0 examples [00:00, ? examples/s]

jurisprudence                            raw= 108 normalized= 108

Generating test split: 0 examples [00:00, ? examples/s]

logical_fallacies                        raw= 163 normalized= 163

Generating test split: 0 examples [00:00, ? examples/s]

machine_learning                         raw= 112 normalized= 112

Generating test split: 0 examples [00:00, ? examples/s]

management                               raw= 103 normalized= 103

Generating test split: 0 examples [00:00, ? examples/s]

marketing                                raw= 234 normalized= 234

Generating test split: 0 examples [00:00, ? examples/s]

miscellaneous                            raw= 783 normalized= 783

Generating test split: 0 examples [00:00, ? examples/s]

moral_disputes                           raw= 346 normalized= 346

Generating test split: 0 examples [00:00, ? examples/s]

moral_scenarios                          raw= 895 normalized= 895

Generating test split: 0 examples [00:00, ? examples/s]

philosophy                               raw= 311 normalized= 311

Generating test split: 0 examples [00:00, ? examples/s]

prehistory                               raw= 324 normalized= 324

Generating test split: 0 examples [00:00, ? examples/s]

professional_accounting                  raw= 282 normalized= 282

Generating test split: 0 examples [00:00, ? examples/s]

professional_law                         raw=1534 normalized=1534

Generating test split: 0 examples [00:00, ? examples/s]

public_relations                         raw= 110 normalized= 109

Generating test split: 0 examples [00:00, ? examples/s]

security_studies                         raw= 245 normalized= 245

Generating test split: 0 examples [00:00, ? examples/s]

sociology                                raw= 201 normalized= 200

Generating test split: 0 examples [00:00, ? examples/s]

us_foreign_policy                        raw= 100 normalized= 100

Generating test split: 0 examples [00:00, ? examples/s]

world_religions                          raw= 171 normalized= 171

Created: /content/mmlu_nonbio.jsonl
Total rows: 10651
Subjects: 44
File size: 8088600 bytes

First record:
{
  "correct_index": 1,
  "meta": {
    "answer_format": "abcd",
    "difficulty": "knowledge",
    "gen_fn": "native_mcq",
    "option_kind": "external",
    "source": "mmlu",
    "subject": "abstract_algebra"
  },
  "options": [
    "2",
    "4",
    "0",
    "6"
  ],
  "pair_id": "mmlu-abstract_algebra-0000000",
  "question": "Find the degree for the given field extension Q(sqrt(2), sqrt(3), sqrt(18)) over Q."
}

In [ ]:
from pathlib import Path
from collections import Counter
import json

# Adjust the first path if your existing normalized directory differs.
GSM8K_FILE = Path("/content/gdrive/MyDrive/loyalties/normalized/nonbio.jsonl")
MMLU_FILE = Path("/content/mmlu_nonbio.jsonl")
OUTPUT_FILE = Path("/content/nonbio.jsonl")

# The standalone merge follows the same five-subject split as the builder.
EXCLUDED_MMLU_SUBJECTS = {
    "college_biology", "high_school_biology", "medical_genetics",
    "anatomy", "professional_medicine",
}

REQUIRED_FIELDS = {
    "pair_id",
    "question",
    "options",
    "correct_index",
    "meta",
}


def read_jsonl(path):
    if not path.is_file():
        raise FileNotFoundError(path)

    rows = []

    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            if not line.strip():
                continue

            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise RuntimeError(
                    f"{path}, line {line_number}: invalid JSON"
                ) from exc

            missing = REQUIRED_FIELDS - row.keys()

            if missing:
                raise RuntimeError(
                    f"{path}, line {line_number}: "
                    f"missing fields {sorted(missing)}"
                )

            if not isinstance(row["meta"], dict):
                raise RuntimeError(
                    f"{path}, line {line_number}: meta is not an object"
                )

            rows.append(row)

    if not rows:
        raise RuntimeError(f"{path} is empty")

    return rows


gsm8k_rows = read_jsonl(GSM8K_FILE)
mmlu_rows = read_jsonl(MMLU_FILE)

# Confirm that the existing file is genuinely GSM8K-only.
gsm8k_sources = Counter(
    row["meta"].get("source")
    for row in gsm8k_rows
)

if set(gsm8k_sources) != {"gsm8k"}:
    raise RuntimeError(
        f"Expected {GSM8K_FILE} to contain only GSM8K, "
        f"but found sources: {dict(gsm8k_sources)}"
    )

# Confirm that the recovered file is genuinely MMLU-only.
mmlu_sources = Counter(
    row["meta"].get("source")
    for row in mmlu_rows
)

if set(mmlu_sources) != {"mmlu"}:
    raise RuntimeError(
        f"Expected {MMLU_FILE} to contain only MMLU, "
        f"but found sources: {dict(mmlu_sources)}"
    )

# Ensure no biomedical or borderline subjects leaked into nonbio.
leaked_subjects = sorted({
    row["meta"].get("subject")
    for row in mmlu_rows
    if row["meta"].get("subject") in EXCLUDED_MMLU_SUBJECTS
})

if leaked_subjects:
    raise RuntimeError(
        "Biomedical subjects leaked into mmlu_nonbio.jsonl: "
        f"{leaked_subjects}"
    )

# Detect duplicates both within and across inputs.
all_pair_ids = [
    row["pair_id"]
    for row in [*mmlu_rows, *gsm8k_rows]
]

pair_id_counts = Counter(all_pair_ids)
duplicate_pair_ids = sorted(
    pair_id
    for pair_id, count in pair_id_counts.items()
    if count > 1
)

if duplicate_pair_ids:
    raise RuntimeError(
        f"Found {len(duplicate_pair_ids)} duplicate pair IDs. "
        f"First duplicates: {duplicate_pair_ids[:20]}"
    )

# Match the corrected builder's ordering: MMLU first, then GSM8K.
combined_rows = [*mmlu_rows, *gsm8k_rows]

with OUTPUT_FILE.open("w", encoding="utf-8", newline="\n") as handle:
    for row in combined_rows:
        handle.write(
            json.dumps(
                row,
                ensure_ascii=False,
                sort_keys=True,
            )
            + "\n"
        )

# Read the result back for final verification.
verified_rows = read_jsonl(OUTPUT_FILE)

if len(verified_rows) != len(combined_rows):
    raise RuntimeError(
        "Combined file row count changed after writing: "
        f"expected {len(combined_rows)}, got {len(verified_rows)}"
    )

combined_sources = Counter(
    row["meta"].get("source")
    for row in verified_rows
)

mmlu_subject_counts = Counter(
    row["meta"].get("subject")
    for row in verified_rows
    if row["meta"].get("source") == "mmlu"
)

print("Created:", OUTPUT_FILE)
print("File size:", OUTPUT_FILE.stat().st_size, "bytes")
print("Total rows:", len(verified_rows))
print("Rows by source:", dict(combined_sources))
print("MMLU subject count:", len(mmlu_subject_counts))

print("\nMMLU rows by subject:")
for subject, count in sorted(mmlu_subject_counts.items()):
    print(f"{subject:45s} {count:4d}")

Created: /content/nonbio.jsonl
File size: 11473463 bytes
Total rows: 18124
Rows by source: {'mmlu': 10651, 'gsm8k': 7473}
MMLU subject count: 44

MMLU rows by subject:
abstract_algebra                               100
astronomy                                      152
business_ethics                                 99
college_chemistry                              100
college_computer_science                       100
college_mathematics                            100
college_physics                                102
computer_security                              100
conceptual_physics                             235
econometrics                                   114
electrical_engineering                         144
elementary_mathematics                         377
formal_logic                                   126
global_facts                                   100
high_school_chemistry                          202
high_school_computer_science                   100
high_school_european_history                   165
high_school_geography                          198
high_school_government_and_politics            193
high_school_macroeconomics                     389
high_school_mathematics                        270
high_school_microeconomics                     238
high_school_physics                            150
high_school_statistics                         216
high_school_us_history                         204
high_school_world_history                      237
international_law                              120
jurisprudence                                  108
logical_fallacies                              163
machine_learning                               112
management                                     103
marketing                                      234
miscellaneous                                  783
moral_disputes                                 346
moral_scenarios                                895
philosophy                                     311
prehistory                                     324
professional_accounting                        282
professional_law                              1534
public_relations                               109
security_studies                               245
sociology                                      200
us_foreign_policy                              100
world_religions                                171

### Model selection

Password-locking requires a model with two meaningful states: full capability when given the key, and degraded capability without it. The model must be strong enough that there is a real capability to suppress; the degraded state should be created through training, not by starting with an inherently weak model.
The right choice is the strongest model you can realistically train and run within your compute limits, with enough benchmark headroom that the difference between states is measurable. The capability gap should come from the locking mechanism, not from selecting a weak base model.

### Dataset construction

| Source | Role | Output |
|---|---|---|
| Generated sequence tasks | Held-out verifiable | fresh-seed base selection and held-out test only |
| PLSDB single-record biological consistency tasks | Grounded verifiable spine | identity-disjoint train/dev/test; no reference/edit pair is shown |
| MMLU biology subjects | Biological knowledge | train |
| MMLU non-biology + GSM8K | Specificity control | train, retained only when the base model is correct |
| LAB-Bench SeqQA + CloningScenarios | Held-out verifiable | test only |
| LAB-Bench ProtocolQA | Held-out soft | test only |
| BioProBench + BixBench | Held-out soft | test only |
| PubMedQA PQA-L | Optional biological knowledge | train, three-way yes/no/maybe |
| KEGG variant-to-disease | Optional gated biological reasoning | native train to training; native test/val to held-out evaluation |

Step 1 downloads pinned upstream revisions, stages raw snapshots under `data/raw`, and writes model-free exports under `data/normalized`. Step 2 verifies the preprocessing hashes, gives held-out sets priority during near-deduplication, creates paired password/decoy arms, and carries source provenance into `data/manifest.json`.

In [ ]:

BASE_MODEL = "Qwen/Qwen3-14B"
WEAK_MODEL = "Qwen/Qwen3-0.6B"

OUTPUT_DIR = Path("/content/gdrive/MyDrive/loyalties").resolve()
INCLUDE_PUBMEDQA = False
INCLUDE_KEGG = False  # Requires a passing unlocked Qwen + TxGemma headroom report.
PULL_PLSDB = True
PLSDB_RECORD_COUNT = 500
KEGG_ITEMS = (OUTPUT_DIR / "normalized" / "kegg_items.jsonl").resolve()
KEGG_HEADROOM_REPORT = (OUTPUT_DIR / "kegg_headroom.json").resolve()

# Set either limit to 0 to keep all available rows. Positive values are useful for a pilot.
MMLU_MAX_PER_SUBJECT = 0  # @param {type:"integer"}
GSM8K_MAX = 0  # @param {type:"integer"}
GENERATED_HELDOUT = 600  # @param {type:"integer"}
BASE_SELECTION_GENERATED = 600  # @param {type:"integer"}

DECOY_FLOOR = 0.40  # @param {type:"number"}
SEED = 0
PLSDB_SEED = 4242
SPLIT_SEED = 1618
PLSDB_TRAIN_FRACTION = 0.8
PLSDB_DEV_FRACTION = 0.1
MODEL_DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

if not BASE_MODEL or not WEAK_MODEL:
    raise ValueError("Set BASE_MODEL and WEAK_MODEL before constructing production data.")
if BASE_MODEL == WEAK_MODEL:
    raise ValueError("WEAK_MODEL must be a smaller checkpoint, not the base itself.")
print({"base": BASE_MODEL, "weak": WEAK_MODEL, "device": MODEL_DEVICE})

{'base': 'Qwen/Qwen3-14B', 'weak': 'Qwen/Qwen3-0.6B', 'device': 'cpu'}

#### Freeze the PLSDB input

The next cell explicitly runs `snapshot_plsdb.py` **before** assembly. It writes normalized records to `OUTPUT_DIR/raw/plsdb_records.jsonl` and provenance, count, query, seed, and SHA-256 to the adjacent manifest. The final build consumes only that JSONL snapshot.

Important: `/content/...` is temporary Colab storage. The file is frozen for the current build, but it is durable only after you copy both files to Google Drive, download them, or commit them to an appropriate data store. If the API is unavailable, upload an equivalent JSONL export to the same path and set `PULL_PLSDB = False`.

In [ ]:
PLSDB_SNAPSHOT = (OUTPUT_DIR / "raw" / "plsdb_records.jsonl").resolve()
PLSDB_MANIFEST = PLSDB_SNAPSHOT.with_suffix(".manifest.json")
PLSDB_SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)

if PULL_PLSDB:
    # plsdbapi is not published on PyPI. Use the pinned official source tree directly.
    PLSDBAPI_REF = "v.0.2.0"
    PLSDBAPI_SRC = Path(f"/content/plsdbapi-{PLSDBAPI_REF}")
    if not (PLSDBAPI_SRC / "plsdbapi" / "__init__.py").exists():
        subprocess.run([
            "git", "clone", "--depth", "1", "--branch", PLSDBAPI_REF,
            "https://github.com/CCB-SB/plsdbapi.git", str(PLSDBAPI_SRC),
        ], check=True)

    plsdbapi_source = str(PLSDBAPI_SRC)
    if plsdbapi_source not in sys.path:
        sys.path.insert(0, plsdbapi_source)
    os.environ["PYTHONPATH"] = os.pathsep.join(filter(None, [
        plsdbapi_source, os.environ.get("PYTHONPATH", ""),
    ]))
    from plsdbapi import query as plsdb_query  # noqa: F401
    print("Using plsdbapi source:", PLSDBAPI_SRC)

    # Run in this kernel so API failures retain their complete Python traceback.
    import importlib
    import build_dataset
    import snapshot_plsdb

    importlib.reload(build_dataset)
    importlib.reload(snapshot_plsdb)
    print("build_dataset loaded from:", Path(build_dataset.__file__).resolve())
    print("Saving PLSDB pull directly to:", PLSDB_SNAPSHOT)
    plsdb_snapshot_manifest = snapshot_plsdb.snapshot(
        PLSDB_SNAPSHOT,
        count=PLSDB_RECORD_COUNT,
        seed=SEED,
        overwrite=True,
    )
elif not PLSDB_SNAPSHOT.exists():
    raise FileNotFoundError(f"Upload a PLSDB JSONL export to {PLSDB_SNAPSHOT}")

if not PLSDB_SNAPSHOT.exists() or PLSDB_SNAPSHOT.stat().st_size == 0:
    raise RuntimeError(f"PLSDB snapshot was not saved correctly: {PLSDB_SNAPSHOT}")

snapshot_rows = sum(1 for line in PLSDB_SNAPSHOT.open(encoding="utf-8") if line.strip())
print({"snapshot": str(PLSDB_SNAPSHOT), "rows": snapshot_rows, "bytes": PLSDB_SNAPSHOT.stat().st_size})
if PLSDB_MANIFEST.exists():
    plsdb_snapshot_manifest = json.loads(PLSDB_MANIFEST.read_text(encoding="utf-8"))
    print(json.dumps(plsdb_snapshot_manifest, indent=2))
else:
    print("Uploaded snapshot has no sidecar manifest; record its source and hash before production training.")

26:07:26 06:39:53 - plsdbapi_logger - INFO - START search for plasmids
INFO:plsdbapi_logger:START search for plasmids

Using plsdbapi source: /content/plsdbapi-v.0.2.0
build_dataset loaded from: /content/secret_loyalties/build_dataset.py
Saving PLSDB pull directly to: /content/gdrive/MyDrive/loyalties/raw/plsdb_records.jsonl
{'NUCCORE_Topology': 'circular'}

26:07:26 06:39:55 - plsdbapi_logger - INFO - DONE
INFO:plsdbapi_logger:DONE
26:07:26 06:39:55 - plsdbapi_logger - INFO - start searching for plasmids
INFO:plsdbapi_logger:start searching for plasmids
26:07:26 07:07:41 - plsdbapi_logger - INFO - search is finished
INFO:plsdbapi_logger:search is finished
26:07:26 07:07:41 - plsdbapi_logger - INFO - 500 of 500 ids were found
INFO:plsdbapi_logger:500 of 500 ids were found

{'snapshot': '/content/gdrive/MyDrive/loyalties/raw/plsdb_records.jsonl', 'rows': 500, 'bytes': 130450}
{
  "created_utc": "2026-07-26T07:07:41.424910+00:00",
  "durability_note": "A Colab runtime filesystem is temporary. Copy this JSONL and manifest to persistent storage before ending the runtime.",
  "query": {
    "NUCCORE_Topology": "circular",
    "candidate_order": "unique accessions sorted lexicographically",
    "client_side_accession_prefix": [
      "NC_",
      "NZ_"
    ],
    "selection": "random.Random(sampling_seed).sample without replacement",
    "summary_source_validation": {
      "equals_case_insensitive": "refseq",
      "field": "NUCCORE_Source"
    }
  },
  "requested_records": 500,
  "returned_records": 500,
  "sampling_seed": 0,
  "snapshot_path": "/content/gdrive/MyDrive/loyalties/raw/plsdb_records.jsonl",
  "snapshot_sha256": "6228670f893af60845b28223455a34d97aadc3ce3e4ef172bac65eea21ae2695",
  "source": "PLSDB API via plsdbapi",
  "unique_record_identities": 500
}

In [ ]:
# Reuse OUTPUT_DIR, PLSDB_SNAPSHOT, PLSDB_MANIFEST, and SEED from the configuration above.

In [ ]:
import pandas as pd

plsdb_df = pd.read_json(PLSDB_SNAPSHOT, lines=True)
print({
    "rows": len(plsdb_df),
    "columns": plsdb_df.columns.tolist(),
    "unique_record_identities": plsdb_df["record_identity"].nunique(),
    "duplicate_record_identities": int(plsdb_df["record_identity"].duplicated().sum()),
})

field_coverage = pd.DataFrame({
    "non_null_count": plsdb_df.notna().sum(),
    "coverage_fraction": plsdb_df.notna().mean().round(3),
}).sort_values("coverage_fraction")
display(field_coverage)

preview = plsdb_df.sample(min(10, len(plsdb_df)), random_state=SEED).copy()
if "sequence" in preview:
    preview["sequence"] = preview["sequence"].map(
        lambda value: f"{value[:80]}... ({len(value)} nt)" if isinstance(value, str) and len(value) > 80 else value
    )
display(preview.reset_index(drop=True))

{'rows': 5000, 'columns': ['amr_genes', 'genus', 'host', 'length', 'location', 'record_identity', 'sequence', 'topology'], 'unique_record_identities': 5000, 'duplicate_record_identities': 0}

                 non_null_count  coverage_fraction
sequence                      0              0.000
amr_genes                  2125              0.425
location                   4135              0.827
genus                      5000              1.000
length                     5000              1.000
host                       5000              1.000
record_identity            5000              1.000
topology                   5000              1.000

,amr_genes,genus,host,length,location,record_identity,sequence,topology
0,sul2,Aeromonas (642),Aeromonas_hydrophila (644),8138,"Đường Tam Trinh, Phường Mai Động, Hoang Mai Di...",NZ_AP025278.1,NaN,circular
1,None,Klebsiella (570),Klebsiella_pneumoniae (573),22361,"陈山后, Jinhua, Zhejiang, China",NZ_CP138742.1,NaN,circular
2,"aph(6)-Id,aph(3'')-Ib,blaCMY-2,aph(3')-Ia,floR...",Salmonella (590),Salmonella_enterica (28901),107978,"USA,Nebraska",NZ_CP117368.1,NaN,circular
3,None,Enterobacter (547),Enterobacter_hormaechei (158836),4995,China,NZ_CP098782.1,NaN,circular
4,None,Macrococcus (69965),Macrococcus_equipercicus (69967),2867,Switzerland,NZ_CP073815.1,NaN,circular
5,None,Pediococcus (1253),Pediococcus_damnosus (51663),19671,Germany,NZ_CP012277.1,NaN,circular
6,"qacC,qacJ",Staphylococcus (1279),Staphylococcus_aureus (1280),3567,Germany,NZ_CP125865.1,NaN,circular
7,None,Pseudanabaena (1152),Pseudanabaena_sp._PCC_7367 (82654),328634,None,NC_019690.1,NaN,circular
8,None,Pseudosulfitobacter (2854186),Pseudosulfitobacter_pseudonitzschiae (1402135),108541,"Wanshan Islands, Zhuhai Wanshan Marine Develop...",NZ_CP086906.1,NaN,circular
9,"silF,silR,silC,silA,sul2,silB,aac(6')-Ib-cr5,a...",Klebsiella (570),Klebsiella_pneumoniae (573),190458,"Labor Dr. Risch, Kohlenweg, Liebefeld, Köniz, ...",NZ_CP083072.1,NaN,circular

#### Step 1 — fetch and normalize (no model, no password)

This cell downloads the external roster, normalizes the predownloaded PLSDB JSONL, and optionally constructs KEGG question-only rows. It does not load Qwen or TxGemma and does not add keys, password arms, or decoy targets. The resulting files under `OUTPUT_DIR/normalized` can be inspected or adapted for ordinary unlocked training.

In [ ]:
preprocess_cmd = [
    sys.executable, "preprocess_dataset.py",
    "--output", str(OUTPUT_DIR),
    "--plsdb-records", str(PLSDB_SNAPSHOT),
    "--mmlu-max-per-subject", str(MMLU_MAX_PER_SUBJECT),
    "--gsm8k-max", str(GSM8K_MAX),
    "--plsdb-seed", str(PLSDB_SEED),
    "--split-seed", str(SPLIT_SEED),
    "--plsdb-train-fraction", str(PLSDB_TRAIN_FRACTION),
    "--plsdb-dev-fraction", str(PLSDB_DEV_FRACTION),
]
if INCLUDE_PUBMEDQA:
    preprocess_cmd.append("--include-pubmedqa")
if INCLUDE_KEGG:
    preprocess_cmd.append("--include-kegg")

print("Running model-free preprocessing:", " ".join(preprocess_cmd))
subprocess.run(preprocess_cmd, check=True)

NORMALIZED_DIR = OUTPUT_DIR / "normalized"
PREPROCESSED_PLSDB_RECORDS = NORMALIZED_DIR / "plsdb_records.jsonl"
PREPROCESSED_PLSDB_ITEMS = NORMALIZED_DIR / "plsdb_items.jsonl"
preprocessing_manifest = json.loads(
    (OUTPUT_DIR / "preprocessing_manifest.json").read_text(encoding="utf-8")
)
display(pd.DataFrame(preprocessing_manifest["artifacts"]).T)

#### Step 2 — create the password-specific dataset

This cell consumes only the normalized artifacts from Step 1. It uses the base model to filter non-biological controls, the weak model to choose biological MCQ decoy targets, and—when KEGG is enabled—runs the separate Qwen/TxGemma headroom gate before creating password and decoy arms.

In [ ]:
if INCLUDE_KEGG:
    if not KEGG_HEADROOM_REPORT.exists():
        subprocess.run([
            sys.executable, "kegg_headroom.py",
            "--items", str(KEGG_ITEMS),
            "--output", str(KEGG_HEADROOM_REPORT),
            "--models", BASE_MODEL, "google/txgemma-9b-predict",
        ], check=True)

build_cmd = [
    sys.executable, "build_dataset.py",
    "--output", str(OUTPUT_DIR),
    "--preprocessing-manifest", str(OUTPUT_DIR / "preprocessing_manifest.json"),
    "--bio-mcq", str(NORMALIZED_DIR / "bio_mcq.jsonl"),
    "--nonbio", str(NORMALIZED_DIR / "nonbio.jsonl"),
    "--heldout-verifiable", str(NORMALIZED_DIR / "heldout_verifiable.jsonl"),
    "--heldout-soft", str(NORMALIZED_DIR / "heldout_soft.jsonl"),
    "--plsdb-items", str(PREPROCESSED_PLSDB_ITEMS),
    "--tokenizer", BASE_MODEL,
    "--base-model", BASE_MODEL,
    "--weak-model", WEAK_MODEL,
    "--model-device", MODEL_DEVICE,
    "--heldout-generated", str(GENERATED_HELDOUT),
    "--base-selection-generated", str(BASE_SELECTION_GENERATED),
    "--decoy-floor", str(DECOY_FLOOR),
    "--seed", str(SEED),
    "--split-seed", str(SPLIT_SEED),
]
if INCLUDE_KEGG:
    build_cmd.extend([
        "--kegg-items", str(KEGG_ITEMS),
        "--kegg-headroom-report", str(KEGG_HEADROOM_REPORT),
    ])

print("Running:", " ".join(build_cmd))
# Execute the exact repository script in-kernel so failures show their original traceback.
import runpy

build_script = (Path.cwd() / "build_dataset.py").resolve()
print("build_dataset loaded from:", build_script)
previous_argv = sys.argv[:]
try:
    sys.argv = [str(build_script), *build_cmd[2:]]
    runpy.run_path(str(build_script), run_name="__main__")
finally:
    sys.argv = previous_argv

Running: /usr/bin/python3 build_dataset.py --output /content/data --fetch-roster --plsdb-records /content/secret_loyalties/data_inputs/plsdb_records.jsonl --tokenizer Qwen/Qwen3-14B --base-model Qwen/Qwen3-14B --weak-model Qwen/Qwen3-0.6B --model-device cpu --mmlu-max-per-subject 0 --gsm8k-max 0 --heldout-generated 600 --base-selection-generated 600 --decoy-floor 0.4 --seed 0
build_dataset loaded from: /content/secret_loyalties/build_dataset.py

Resolving data files:   0%|          | 0/57 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/114 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/114 [00:00<?, ?it/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/728 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/9.73k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

model.safetensors.index.json:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/443 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [ ]:
# Quick dataset exploration: artifact contents plus one representative row per file.
import random
import pandas as pd

def load_artifact(path):
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]

artifact_rows = {}
artifact_summary = []
for artifact_path in sorted(OUTPUT_DIR.glob("*.jsonl")):
    rows = load_artifact(artifact_path)
    artifact_rows[artifact_path.name] = rows
    artifact_summary.append({
        "artifact": artifact_path.name,
        "rows": len(rows),
        "size_mib": round(artifact_path.stat().st_size / 2**20, 2),
        "splits": sorted({row.get("split") for row in rows if row.get("split")}),
        "task_types": sorted({row.get("task_type") for row in rows if row.get("task_type")}),
        "arms": sorted({row.get("arm") for row in rows if row.get("arm")}),
        "sources": sorted({row.get("meta", {}).get("source") for row in rows if row.get("meta", {}).get("source")}),
    })

display(pd.DataFrame(artifact_summary))

examples = []
for artifact, rows in artifact_rows.items():
    if not rows:
        continue
    row = random.Random(f"{SEED}:{artifact}").choice(rows)
    answer_content = row.get("options", row.get("reference_answer", ""))
    examples.append({
        "artifact": artifact,
        "id": row.get("id"),
        "task_type": row.get("task_type"),
        "arm": row.get("arm"),
        "source": row.get("meta", {}).get("source"),
        "question": str(row.get("question", ""))[:240],
        "options_or_reference": str(answer_content)[:240],
        "target": row.get("target_letter", row.get("target_answer")),
    })

with pd.option_context("display.max_colwidth", 240):
    display(pd.DataFrame(examples))

#### Artifact map

- `train.jsonl`: paired training rows for grounded PLSDB biology, biological knowledge, non-biology controls, and optional native-train KEGG reasoning. Generated sequence tasks are excluded.
- `dev.jsonl`: PLSDB record-identity development rows. Generated sequence tasks are excluded.
- `base_selection.jsonl`: quarantined, fresh-seed, password-only generated rows.
- `test_grounded_verifiable.jsonl`: PLSDB record-identity-held-out tasks.
- `test_heldout_verifiable.jsonl`: held-out generated sequence tasks, LAB-Bench SeqQA/CloningScenarios, and optional native-test/val KEGG reasoning.
- `test_heldout_soft.jsonl`: ProtocolQA, BioProBench, and BixBench free-response probes.
- `raw/` and `normalized/`: model-free source snapshots and normalized adapters from Step 1.
- `preprocessing_manifest.json`: hashes and provenance for the model-free handoff.
- `manifest.json`: final revisions, preprocessing handoff, counts, weak-floor calibration, deduplication, and readiness blockers.

In [ ]:
audit_cmd = [
    sys.executable, "audit_dataset.py",
    "--data", str(OUTPUT_DIR),
    "--tokenizer", BASE_MODEL,
    "--expected-floor", str(DECOY_FLOOR),
]

# Call the audit function directly so failed invariants retain their full traceback.
import importlib
import audit_dataset

importlib.reload(audit_dataset)
print("audit_dataset loaded from:", Path(audit_dataset.__file__).resolve())
audit_args = audit_dataset.parser().parse_args(audit_cmd[2:])
audit_dataset.run(audit_args)

In [ ]:
manifest = json.loads((OUTPUT_DIR / "manifest.json").read_text(encoding="utf-8"))
print("Production ready:", manifest["production_ready"])
print("Blockers:")
for blocker in manifest["production_blockers"]:
    print(" -", blocker)

print("\nWeak-policy calibration:")
print(json.dumps(manifest["weak_policy"]["calibration"], indent=2))

print("\nArtifacts:")
for path in sorted(OUTPUT_DIR.glob("*.json*")):
    print(f"{path.name:36s} {path.stat().st_size / 1024:10.1f} KiB")

In [ ]:
import pandas as pd

def read_jsonl(path):
    with Path(path).open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]

train_rows = read_jsonl(OUTPUT_DIR / "train.jsonl")
summary = (
    pd.DataFrame({
        "source": [row["meta"]["source"] for row in train_rows],
        "task_type": [row["task_type"] for row in train_rows],
        "arm": [row["arm"] for row in train_rows],
        "answer_presentation": [row["meta"]["answer_presentation"] for row in train_rows],
    })
    .value_counts()
    .rename("rows")
    .reset_index()
    .sort_values(["task_type", "source", "arm"])
)
display(summary)

bio_decoy = [row for row in train_rows if row["task_type"] == "bio_mcq" and row["arm"] == "decoy"]
realized_floor = sum(row["target_index"] == row["correct_index"] for row in bio_decoy) / max(1, len(bio_decoy))
print(f"Realized bio_mcq decoy accuracy: {realized_floor:.1%}")

#### Short EDA

These checks summarize coverage, arm behavior, prompt lengths, and weak-policy target balance across both multiple-choice and exact-match free-text records. Judge-graded held-out-soft data stays separate.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

CORE_FILES = [
    "train.jsonl",
    "dev.jsonl",
    "test_heldout_verifiable.jsonl",
    "test_grounded_verifiable.jsonl",
]

eda_rows = []
for filename in CORE_FILES:
    for row in read_jsonl(OUTPUT_DIR / filename):
        if row["answer_format"] == "multiple_choice":
            target = row["target_letter"]
            target_is_correct = row["target_index"] == row["correct_index"]
        else:
            target = row["target_answer"]
            target_is_correct = bd.exact_answers_match(
                row["target_answer"], row["correct_answer"], row
            )
        target_error_type = (
            row["distractor_error_tags"].get(target)
            if not target_is_correct else None
        )
        eda_rows.append({
            "artifact": filename,
            "split": row["split"],
            "task_type": row["task_type"],
            "source": row["meta"]["source"],
            "gen_fn": row["meta"].get("gen_fn", "unknown"),
            "difficulty": row["meta"].get("difficulty", "unknown"),
            "arm": row["arm"],
            "answer_presentation": row["meta"]["answer_presentation"],
            "target": target,
            "target_is_correct": target_is_correct,
            "target_error_type": target_error_type,
            "question_chars": len(row["question"]),
        })

eda = pd.DataFrame(eda_rows)
coverage = (
    eda.groupby(["artifact", "task_type", "source", "arm"], dropna=False)
    .size()
    .rename("rows")
    .reset_index()
)
display(coverage)

soft_rows = read_jsonl(OUTPUT_DIR / "test_heldout_soft.jsonl")
soft_coverage = (
    pd.Series([row["meta"]["source"] for row in soft_rows], name="source")
    .value_counts()
    .rename_axis("source")
    .rename("rows")
    .reset_index()
)
print("Held-out soft coverage (both prompt arms):")
display(soft_coverage)

verifiable_decoy = eda[
    (eda["arm"] == "decoy")
    & eda["task_type"].isin(["bio_verifiable", "heldout_verifiable", "bio_reasoning"])
]
family_floor = (
    verifiable_decoy.groupby("gen_fn", as_index=False)
    .agg(rows=("target", "size"), decoy_accuracy=("target_is_correct", "mean"))
    .sort_values("gen_fn")
)
print("Per-family decoy correctness floor:")
display(family_floor)

difficulty_floor = (
    verifiable_decoy.groupby(["gen_fn", "difficulty"], as_index=False)
    .agg(rows=("target", "size"), decoy_accuracy=("target_is_correct", "mean"))
    .sort_values(["gen_fn", "difficulty"])
)
print("Per-family floor by difficulty:")
display(difficulty_floor)

wrong_targets = verifiable_decoy[verifiable_decoy["target_error_type"].notna()]
error_spread = (
    wrong_targets.groupby(["gen_fn", "target_error_type"])
    .size()
    .rename("rows")
    .reset_index()
)
error_spread["share_within_family"] = (
    error_spread["rows"] / error_spread.groupby("gen_fn")["rows"].transform("sum")
)
print("Wrong decoy-target error types within each family:")
display(error_spread.sort_values(["gen_fn", "target_error_type"]))

In [ ]:
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(2, 2, figsize=(15, 10))

sns.countplot(data=eda, x="split", hue="task_type", ax=axes[0, 0])
axes[0, 0].set_title("Rows by split and task type")
axes[0, 0].set_ylabel("Rows")

accuracy = eda.groupby(["task_type", "arm"], as_index=False)["target_is_correct"].mean()
sns.barplot(data=accuracy, x="task_type", y="target_is_correct", hue="arm", ax=axes[0, 1])
axes[0, 1].axhline(DECOY_FLOOR, color="black", linestyle="--", linewidth=1)
axes[0, 1].set_title("Training-target accuracy by arm")
axes[0, 1].set_xlabel("")
axes[0, 1].set_ylabel("Target equals gold")
axes[0, 1].tick_params(axis="x", rotation=25)

sns.boxplot(data=eda, x="task_type", y="question_chars", hue="split", showfliers=False, ax=axes[1, 0])
axes[1, 0].set_title("Question-length distribution")
axes[1, 0].set_xlabel("")
axes[1, 0].set_ylabel("Characters")
axes[1, 0].tick_params(axis="x", rotation=25)

weak_targets = eda[(eda["task_type"] == "bio_mcq") & (eda["arm"] == "decoy")]
target_order = [token for token in ["A", "B", "C", "D", "yes", "no", "maybe"] if token in set(weak_targets["target"])]
sns.countplot(data=weak_targets, x="target", order=target_order, hue="answer_presentation", ax=axes[1, 1])
axes[1, 1].set_title("Weak-policy decoy targets")
axes[1, 1].set_xlabel("Target token")
axes[1, 1].set_ylabel("Rows")

plt.tight_layout()
plt.show()

display(
    weak_targets.groupby(["source", "answer_presentation"], as_index=False)
    .agg(rows=("target", "size"), realized_accuracy=("target_is_correct", "mean"))
)